server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rms-agent
    username: root
    password: 123456
    max-active: 2
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: true
mybatis:
  logic-delete: true
debug: false